### ISSUE TITLE
Setting any default editor says "specified path does not exist"

### ISSUE THREAD

**Issue by neville-nazerane** [dotnet/HttpRepl#459] opened 2020-12-11 04:03 UTC
I just installed and used: 

`prefset editor.command.default notepad`

This command has worked in the past on other computers. However, now when I run a post, I get the following error:

"The specified default editor path, "notepad", does not exist."

I tried the whole path and still get "The specified default editor path, "C:\Windows\System32\notepad.exe", does not exist.". 

Finally, I tried the exact command from the documentation: 

`pref set editor.command.default "C:\Program Files\Microsoft VS Code\Code.exe"`

I still get: 

The specified default editor path, "C:\Program Files\Microsoft VS Code\Code.exe", does not exist.

Here is the information I get from `dotnet info`

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by tlmii** [comment] 2020-12-11 23:50
It doesn't surprise me that `notepad` by itself would not work - a full path to the executable is required with the current implementation. I'm more surprised that you note that it has ever worked. Perhaps that had something to do work your working directory? Curious...

The documentation happens to specify the not-default-anymore system setup installation location for VS Code. The new default location (user setup) would be more like `c:\users\{username}\appdata\local\programs\microsoft vs code\code.exe`. Not sure if that is the cause of your issue there, though.

The full path notepad part is very odd though. Under the hood, that error comes from doing a simple [File.Exists(...)](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.exists?view=net-5.0) on the value of the preference. 

What terminal are you using to run httprepl? I'm wondering if it might not have access for some reason.

Could you try a blank .NET 5 console app, and call File.Exists with the values you're specifying here and see if they succeed? Preferably run your command from the same terminal/working directory as you're running httprepl as well.

**Comment by tlmii** [comment] 2020-12-15 08:21
@neville-nazerane - just checking in to see if you had a chance to try any of the above?

**Comment by neville-nazerane** [comment] 2020-12-15 08:55
Yes. You were right about the vs link being wrong. 

I tried it again with the notepad path mentioned and it worked fine. I am no longer able to reproduce the issue. 

I am guessing the issue was either 

- I didn't test it right the first time (I had a PS and CMD tab open and I was messy). Might be I set default in one tab and tested in the second without re-opening 

OR

- it's something thing to do with the preview sdk that comes with VS. Somewhere in between I installed the .net 5 stable. I tried uninstalling this to narrow down the issue. However the uninstall tool didn't work. 
I can verify if its the SDK this weekend.

**Comment by tlmii** [comment] 2020-12-15 18:54
OK, sounds good. I'm going to go ahead and close the issue since it doesn't repro anymore. The first scenario you described would _definitely_ cause what you saw, so that may be it. If you find something related to the preview SDK, feel free to file another issue with the specifics and we can help get the info to the right folks.

**Closed by tlmii** 2020-12-15 18:54 UTC
Labels: waiting
