### ISSUE TITLE
Could not execute because the specified command or file was not found.

### ISSUE THREAD

**Issue by jsacapdev** [dotnet/HttpRepl#255] opened 2019-10-06 14:15 UTC
When trying to run the tool, the following is reported back:

```
PS C:\git\hal\ftc> dotnet httprepl http://localhost:65369/
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-httprepl does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

This is the following i get back when I try and install it again:

```
PS C:\git\hal\ftc> dotnet tool install --global Microsoft.dotnet-httprepl --version 3.0.47301
Tool 'microsoft.dotnet-httprepl' is already installed.
```

FYI:

```
PS C:\git\hal\ftc> dotnet --list-sdks
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.503 [C:\Program Files\dotnet\sdk]
2.1.504 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]
2.1.507 [C:\Program Files\dotnet\sdk]
2.1.508 [C:\Program Files\dotnet\sdk]
2.1.509 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.604 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
2.1.701 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
2.1.802 [C:\Program Files\dotnet\sdk]
2.2.102 [C:\Program Files\dotnet\sdk]
2.2.103 [C:\Program Files\dotnet\sdk]
2.2.104 [C:\Program Files\dotnet\sdk]
2.2.105 [C:\Program Files\dotnet\sdk]
2.2.202 [C:\Program Files\dotnet\sdk]
2.2.203 [C:\Program Files\dotnet\sdk]
2.2.204 [C:\Program Files\dotnet\sdk]
2.2.300 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]
2.2.402 [C:\Program Files\dotnet\sdk]
3.0.100 [C:\Program Files\dotnet\sdk]
PS C:\git\hal\ftc>
```

**Comment by tlmii** [comment] 2019-10-07 15:55
Hi @jsacapdev - a few previews before the release we changed the command from `dotnet-httprepl` to just `httprepl`. What that means is that you don't need to (and in fact _can't_) use the `dotnet` command to launch the tool. You just use `httprepl`:

```console
C:\Users\tlmii>dotnet tool list -g
Package Id                     Version        Commands
------------------------------------------------------
microsoft.dotnet-httprepl      3.0.47301      httprepl

C:\Users\tlmii>httprepl
(Disconnected)> connect https://petstore.swagger.io/v2
Using a base address of https://petstore.swagger.io/v2/
Using swagger definition at https://petstore.swagger.io/v2/swagger.json

https://petstore.swagger.io/v2/> exit

C:\Users\tlmii>
```

Give that a shot and see if it works for you. Closing the issue for now unless you indicate the problem is something else.

**Closed by tlmii** 2019-10-07 15:55 UTC

**Comment by jsacapdev** [comment] 2019-10-10 13:59
@tlmii many thanks for your support, this works for me
